# Generated by Django 2.2.3 on 2019-07-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='tags',
            field=models.ManyToManyField(to='links.Tags', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='links',
            name='short_url',
            field=models.CharField(default='oqwpbk', max_length=6),
        ),
    ]
