# Generated by Django 2.2.3 on 2019-07-30 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_auto_20190729_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='original_url',
            field=models.URLField(verbose_name='Оригинальная ссылка'),
        ),
        migrations.AlterField(
            model_name='links',
            name='short_url',
            field=models.CharField(default='XJURE2', max_length=6, verbose_name='Короткая ссылка'),
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('referer', models.URLField(blank=True, verbose_name='Реферер')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=100, verbose_name='Агент')),
                ('short_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='links.Links', verbose_name='Короткая ссылка')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистики',
            },
        ),
    ]
