# Generated by Django 2.2.3 on 2019-07-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_auto_20190730_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='short_url',
            field=models.CharField(default='co5tON', max_length=6, verbose_name='Короткая ссылка'),
        ),
        migrations.DeleteModel(
            name='Statistics',
        ),
    ]
