# Generated by Django 2.2.3 on 2019-07-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_auto_20190730_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='jump',
            field=models.IntegerField(default=0, verbose_name='Переходы'),
        ),
        migrations.AlterField(
            model_name='links',
            name='short_url',
            field=models.CharField(default='eyeGmi', max_length=6, verbose_name='Короткая ссылка'),
        ),
    ]
