# Generated by Django 2.2.3 on 2019-07-31 09:47

from django.db import migrations, models
import links.models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_auto_20190730_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='short_url',
            field=models.CharField(default=links.models.gen_short, max_length=6, unique=True, verbose_name='Короткая ссылка'),
        ),
    ]
